export const majorList = {
  advertisingCreation: '광고홍보학과',
  americanStudies: '미국학과',
  appliedMusic: '실용음악과',
  broadcastingEntertainment: '방연과',
  businessAdministration: '경영학과',
  childYouthWelfare: '아동청소년복지학과',
  chineseStudies: '중국학과',
  computerScience: '컴퓨터학과',
  dataInfomation: '데이터정보학과',
  digitalInformationStatistics: '디지털응용정보학과',
  digitalMediaMotionDesign: '영상디자인학과',
  fashionDesignBranding: '패션디자인및브랜딩학과',
  globalLeaders: '글로벌리더스융복합',
  hawn: '환황해권물류지식인융복합전공',
  informationCommunication: '정보통신학과',
  integratedEnvironmentalSystems: '환경융합시스템학과',
  internationalTradeLogistics: '무역물류학과',
  japaneseStudies: '일본학과',
  koreanLanguageLiterature: '국어국문학과',
  multipleCultures: '다문화복지융복합',
  music: '음악학과',
  nursingScience: '간호학과',
  publicAdministration: '행정학과',
  rehabilitationStudies: '재활복지학과',
  socialWelfare: '사회복지학과',
  startUp: '창업융복합',
  storytelling: '스토리텔링융복합',
  superiorCooperativeLeadership: '초협업',
  theology: '신학과',
  UrbanRealEstate: '도시및부동산개발학과',
  VisualArtDesign: '시각디자인학과',
}

export const nonMajorList = {
  options: '교양선택',
  requirements: '교양필수',
  ptu: 'PTU교양',
}
